import type { Metadata } from 'next';
import { Barlow, Poppins } from 'next/font/google'; // Importing Barlow and Poppins fonts
import localFont from 'next/font/local';
import './globals.css';

// Importing the Barlow font from Google Fonts
const barlow = Barlow({
  subsets: ['latin'],
  variable: '--font-barlow',
  weight: ['400', '600', '700'],
});

// Importing the Poppins font from Google Fonts
const poppins = Poppins({
  subsets: ['latin'],
  variable: '--font-poppins',
  weight: ['400', '500', '600', '700'], // Customize the weights as needed
});

const geistSans = localFont({
  src: './fonts/GeistVF.woff',
  variable: '--font-geist-sans',
  weight: '100 900',
});

const geistMono = localFont({
  src: './fonts/GeistMonoVF.woff',
  variable: '--font-geist-mono',
  weight: '100 900',
});

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${barlow.variable} ${poppins.variable} ${geistSans.variable} ${geistMono.variable} antialiased`}
        style={{ fontFamily: 'var(--font-poppins), var(--font-barlow), sans-serif' }} // Setting Poppins as the primary font
      >
        {children}
      </body>
    </html>
  );
}
